// packages/preact-signals/reference-app/routes/tasks/Tasks.tsx
import type {
  ActionFunction,
  LoaderFunction,
} from "remix-router-preact-signals";
import { Link, Outlet, useLoaderData } from "remix-router-preact-signals";

import { deleteTask, getTasks, ITask } from "~/tasks";
import { sleep } from "~/utils";
import TaskItem from "~/components/TaskItem";

export const loader: LoaderFunction = async () => {
  await sleep();
  return {
    tasks: getTasks(),
  };
};

export const action: ActionFunction = async ({ request }) => {
  console.log("start action");
  await sleep();
  let formData = await request.formData();
  deleteTask(formData.get("taskId") as string);
  console.log("end action");
  return {};
};

export default function Tasks() {
  const data = useLoaderData<{ tasks: ITask[] }>();

  return (
    <>
      <h2>Tasks</h2>
      <ul>
        {data.value.tasks.map((task: ITask) => (
          <li key={task.id}>
            <TaskItem task={task} />
          </li>
        ))}
      </ul>
      <Link to="/tasks/new">Add New Task</Link>
      <Outlet />
    </>
  );
}

// packages/lit/reference-app/routes/tasks/tasks.ts
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";
import { ActionFunctionArgs } from "@remix-run/router";
import { map } from "lit/directives/map.js";
import { ITask, deleteTask, getTasks } from "../../tasks";
import { sleep } from "../../utils";
import { Router } from "remix-router-lit";

export async function loader() {
  await sleep();
  return {
    tasks: getTasks(),
  };
}

export async function action({ request }: ActionFunctionArgs) {
  await sleep();
  let formData = await request.formData();
  deleteTask(formData.get("taskId") as string);
  return {};
}

@customElement("app-tasks")
export class Tasks extends LitElement {
  private router = new Router(this);

  get data() {
    return this.router.loaderData<{ tasks: ITask[] }>();
  }

  render() {
    return html`
      <h2>Tasks</h2>
      <ul>
        ${map(
          this.data?.tasks,
          (task) => html`
            <li>
              <app-task-item .task=${task}></app-task-item>
            </li>
          `
        )}
      </ul>
      <a href="/tasks/new" ${this.router.enhanceLink()}>Add New Task</a>
      <router-outlet></router-outlet>
    `;
  }
}
