// packages/preact-signals/reference-app/routes/Defer.tsx
import { Suspense } from "preact/compat";
import * as React from "react";
import {
  Await,
  defer,
  useAsyncError,
  useLoaderData,
} from "remix-router-preact-signals";

const resolve = (d: string, ms: number): Promise<string> =>
  new Promise((r) => setTimeout(() => r(d), ms));

const reject = (d: string, ms: number) =>
  new Promise((_, r) => setTimeout(() => r(d), ms));

interface LoaderData {
  critical: string;
  lazy: Promise<String>;
  lazyError: Promise<string>;
}

export async function loader() {
  return defer({
    critical: await resolve("Critical Data", 500),
    lazy: resolve("Lazy Data ✅", 1000),
    lazyError: reject("Lazy Error 💥", 1500),
  });
}

function ErrorElement() {
  let error = useAsyncError();
  return <p id="lazy-error">{`Error: ${error}`}</p>;
}

export default function Defer() {
  let data = useLoaderData<LoaderData>();

  return (
    <>
      <p id="critical-data">Critical Data: {data.value.critical}</p>

      <Suspense fallback={<p id="lazy-value">Loading data...</p>}>
        <Await resolve={data.value.lazy}>
          {(value) => <p id="lazy-value">Value: {value}</p>}
        </Await>
      </Suspense>

      <Suspense fallback={<p id="lazy-error">Loading error...</p>}>
        <Await resolve={data.value.lazyError} errorElement={<ErrorElement />}>
          {() => <p>Nope!</p>}
        </Await>
      </Suspense>
    </>
  );
}

// packages/lit/reference-app/routes/defer.ts
import { defer } from "@remix-run/router";
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";
import { Router } from "remix-router-lit";

const resolve = (data: any, ms: number) =>
  new Promise((r) => setTimeout(() => r(data), ms));
const reject = (data: any, ms: number) =>
  new Promise((_, r) => setTimeout(() => r(data), ms));

export async function loader() {
  return defer({
    critical: await resolve("Critical Data", 1000),
    lazy: resolve("Lazy Data ✅", 1000),
    lazyError: reject("Lazy Error 💥", 2000),
  });
}

@customElement("app-defer")
export class Defer extends LitElement {
  private router = new Router(this);

  get data() {
    return this.router.loaderData<{
      critical: string;
      lazy: Promise<string>;
      lazyError: Promise<string>;
    }>();
  }

  render() {
    return html`
      <p id="critical-data">Critical Data: ${this.data?.critical}</p>
      ${this.router.await({
        resolve: this.data?.lazy,
        fallback: html`<p id="lazy-value">Loading data...</p>`,
        template: (value) => html`<p id="lazy-value">Value: ${value}</p>`,
      })}
      ${this.router.await({
        resolve: this.data?.lazyError,
        fallback: html`<p id="lazy-error">Loading error...</p>`,
        template: (value) => html`<p>Value: ${value}</p>`,
        error: (error) => html`<p id="lazy-error">Error: ${error}</p>`,
      })}
    `;
  }
}
