// packages/preact-signals/reference-app/routes/Error.tsx
import type { LoaderFunction } from "@remix-run/router";
import { json, useLoaderData } from "remix-router-preact-signals";

export const loader: LoaderFunction = async ({ request }) => {
  let isLoaderError =
    new URL(request.url).searchParams.get("type") === "loader";
  if (isLoaderError) {
    throw new Error("Loader error!");
  }
  return json({});
};

export default function ErrorComponent() {
  let data = useLoaderData<any>();
  return <h2>Render Error: {data.value.foo.bar}</h2>;
}

// packages/lit/reference-app/routes/error.ts
import { LoaderFunctionArgs, json } from "@remix-run/router";
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";
import { Router } from "remix-router-lit";

export async function loader({ request }: LoaderFunctionArgs) {
  let isLoaderError =
    new URL(request.url).searchParams.get("type") === "loader";
  if (isLoaderError) {
    throw new Error("Loader error!");
  }
  return json({});
}

@customElement("app-error")
export class ErrorElement extends LitElement {
  private router = new Router(this);

  get data() {
    return this.router.loaderData() as any;
  }

  render() {
    return html`<h2>Render Error: ${this.data?.foo.bar}</h2>`;
  }
}
