// packages/preact-signals/reference-app/routes/Redirect.tsx
import type { LoaderFunction } from "@remix-run/router";
import { redirect } from "remix-router-preact-signals";
import { sleep } from "~/utils";

export const loader: LoaderFunction = async ({ request }) => {
  await sleep();
  let location = new URL(request.url).searchParams.get("location") || "/";
  return redirect(location);
};

export default function Redirect() {
  return <h2>Shouldn't see me</h2>;
}

// packages/lit/reference-app/routes/redirect.ts
import { LitElement, html } from "lit"
import { customElement } from "lit/decorators.js"

import { LoaderFunctionArgs, redirect } from "@remix-run/router"
import { sleep } from "../utils"

export async function loader({ request }: LoaderFunctionArgs) {
    await sleep()
    let location = new URL(request.url).searchParams.get("location") || "/"
    return redirect(location)
}

@customElement("app-redirect")
export class Redirect extends LitElement {
    render = () => html`<h2>Shouldn't see me</h2>`
}
