// packages/lit/reference-app/routes/tasks/new-task.ts
import { ActionFunctionArgs, redirect } from "@remix-run/router";
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";
import { Router } from "remix-router-lit";
import { addTask } from "../../tasks";
import { sleep } from "../../utils";

export async function action({ request }: ActionFunctionArgs) {
  await sleep();
  let formData = await request.formData();
  addTask(formData.get("new-task") as string);
  return redirect("/tasks", { status: 302 });
}

@customElement("app-new-task")
export class NewTask extends LitElement {
  router = new Router(this);

  get isAdding() {
    return this.router.navigation.state !== "idle";
  }

  render() {
    return html`
      <h3>New Task</h3>
      <form method="post" ${this.router.enhanceForm()}>
        <input
          name="new-task"
          placeholder="Add a task..."
          ?disabled=${this.isAdding}
        />
        <button type="submit" ?disabled=${this.isAdding}>
          ${this.isAdding ? "Adding..." : "Add"}
        </button>
      </form>
    `;
  }
}

// packages/preact-signals/reference-app/routes/tasks/NewTask.tsx
import { useComputed } from "@preact/signals";
import {
  ActionFunction,
  redirect,
  Form,
  useNavigation,
} from "remix-router-preact-signals";

import { addTask } from "~/tasks";
import { sleep } from "~/utils";

export const action: ActionFunction = async ({ request }) => {
  await sleep();
  let formData = await request.formData();
  addTask(formData.get("newTask") as string);
  return redirect("/tasks", { status: 302 });
};

export default function NewTask() {
  const navigation = useNavigation();
  const isAdding = useComputed(() => navigation.value.state !== "idle");
  const text = useComputed(() => (isAdding.value ? "Adding..." : "Add"));

  return (
    <>
      <h3>New Task</h3>
      <Form method="post" action="/tasks/new">
        <input name="newTask" />
        <button type="submit" disabled={isAdding}>
          {text}
        </button>
      </Form>
    </>
  );
}
