// packages/lit/reference-app/elements/task-item.ts
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";
import { RouterController } from "remix-router-lit";
import { Task } from "../tasks";

@customElement("app-task-item")
export class TaskItem extends LitElement {
  private router = new RouterController(this);

  @property({ attribute: false })
  public task!: Task;

  get fetcher() {
    return this.router.fetcher();
  }

  get isDeleting() {
    return this.fetcher.formData != null;
  }

  render() {
    return html`
      <span>${this.task.task}</span>
      &nbsp;
      <a href=${`/tasks/${this.task.id}`} ${this.router.enhanceLink()}>Open</a>
      &nbsp;

      <form
        ${this.fetcher.enhanceForm()}
        style="display: inline"
        action="/tasks"
        method="post"
      >
        <button
          type="submit"
          name="taskId"
          value="${this.task.id}"
          ?disabled=${this.isDeleting}
        >
          ${this.isDeleting ? "Deleting..." : "❌"}
        </button>
      </form>
    `;
  }
}

// packages/preact-signals/reference-app/components/TaskItem.tsx
import { useComputed } from "@preact/signals";
import { Link, useFetcher } from "remix-router-preact-signals";

import type { Task } from "../tasks";

export interface TaskItemProps {
  task: Task;
}

export default function TaskItem({ task }: TaskItemProps) {
  let { fetcher, Form } = useFetcher();
  let isDeleting = useComputed(() => !!fetcher.value.formData);
  let text = useComputed(() => (isDeleting.value ? "Deleting..." : "❌"));

  return (
    <>
      <span>{task.task}</span> <Link to={`/tasks/${task.id}`}>Open</Link>{" "}
      <Form style={{ display: "inline" }} action="/tasks" method="post">
        <button
          type="submit"
          name="taskId"
          value={task.id}
          disabled={isDeleting}
        >
          {text}
        </button>
      </Form>
    </>
  );
}
