// packages/lit/reference-app/routes/nested/child.ts
import { json } from "@remix-run/router";
import { html, LitElement } from "lit";
import { customElement } from "lit/decorators.js";
import { sleep } from "../../utils";
import { Router } from "remix-router-lit";

interface LoaderData {
  data: string;
}

export async function loader() {
  await sleep();
  return json<LoaderData>({ data: "child loader data" });
}

@customElement("app-child")
export class Child extends LitElement {
  private router = new Router(this);

  get data() {
    return this.router.loaderData<LoaderData>();
  }

  render() {
    return html`
      <h3>Child Route</h3>
      <p id="child">Child data: ${this.data?.data}</p>
    `;
  }
}

// packages/preact-signals/reference-app/routes/nested/Child.tsx
import { LoaderFunction } from "@remix-run/router";
import { json, useLoaderData } from "remix-router-preact-signals";
import { sleep } from "~/utils";

interface LoaderData {
  data: string;
}

export const loader: LoaderFunction = async () => {
  await sleep();
  return json<LoaderData>({ data: "child loader data" });
};

export default function Child() {
  const data = useLoaderData<LoaderData>();

  return (
    <>
      <h3>Child Route</h3>
      <p id="child">Child data: {data.value.data}</p>
    </>
  );
}
