// packages/lit/reference-app/routes/root.ts
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";
import { map } from "lit/directives/map.js";
import { Router } from "remix-router-lit";

@customElement("app-root")
export class Root extends LitElement {
  private router = new Router(this);

  private readonly links = {
    Index: "/",
    Parent: "/parent",
    Child: "/parent/child",
    Redirect: "/redirect?location=%2Fparent%2Fchild",
    "Loader Error": "/error?type=loader",
    "Render Error": "/error?type=render",
    "Nested Loader Error": "/parent/error?type=loader",
    "Nested Render Error": "/parent/error?type=render",
    Defer: "/defer",
    Tasks: "/tasks",
  };

  private get properties() {
    return {
      navigationType: JSON.stringify(this.router.navigationType),
      location: JSON.stringify(this.router.location),
      navigation: JSON.stringify(this.router.navigation),
      matches: JSON.stringify(this.router.matches),
    };
  }

  render() {
    return html`
      <h1>Root Layout (Lit)</h1>
      <nav>
        ${map(
          Object.entries(this.links),
          ([text, href]) =>
            html`<a ${this.router.enhanceLink()} href="${href}">${text}</a> `
        )}
        <button id="back" @click=${() => this.router.navigate(-1)}>
          Go Back
        </button>
      </nav>
      ${map(
        Object.entries(this.properties),
        ([k, v]) => html`
          <p>
            ${k}:
            <code id="${k}">${v}</code>
          </p>
        `
      )}
      <router-outlet></router-outlet>
    `;
  }
}

// packages/preact-signals/reference-app/routes/Root.tsx
import {
  Link,
  Outlet,
  useLocation,
  useMatches,
  useNavigate,
  useNavigation,
  useNavigationType,
} from "remix-router-preact-signals";

export default function Root() {
  let links = {
    Index: "/",
    Parent: "/parent",
    Child: "/parent/child",
    Redirect: "/redirect?location=%2Fparent%2Fchild",
    "Loader Error": "/error?type=loader",
    "Render Error": "/error?type=render",
    "Nested Loader Error": "/parent/error?type=loader",
    "Nested Render Error": "/parent/error?type=render",
    Defer: "/defer",
    Tasks: "/tasks",
  };

  let hooks = {
    useNavigationType: JSON.stringify(useNavigationType()),
    useLocation: JSON.stringify(useLocation()),
    useNavigation: JSON.stringify(useNavigation()),
    useMatches: JSON.stringify(useMatches()),
  };

  let navigate = useNavigate();

  return (
    <>
      <h1>Root Layout (Preact Signals)</h1>
      <nav>
        {Object.entries(links).map(([text, href]) => (
          <Link key={href} to={href}>
            {text}
          </Link>
        ))}
        <button id="back" onClick={() => navigate(-1)}>
          Go Back
        </button>
      </nav>
      {Object.entries(hooks).map(([k, v]) => (
        <p key={k}>
          {k}():
          <code id={k}>{v}</code>
        </p>
      ))}
      <Outlet />
    </>
  );
}
